services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./.db-mongodb:/data/db:delegated

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: backend
    ports:
      - 8008:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo

  frontend:
    build:
      context: frontend          # Now pointing just to the parent folder
      dockerfile: Dockerfile     # The Dockerfile is now directly inside /frontend
    ports:
      - 3000:3000                # You only need one port now!
    working_dir: /frontend
    volumes:                     # (Highly Recommended) Mounts your code for hot-reloading
      - ./frontend:/frontend
      - /frontend/node_modules   # Prevents local node_modules from overwriting container's
    command: npm start
    depends_on:
      - backend

  frontend-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: frontend
    volumes:
      - .:/workspaces/senior-capstone-project # Matches your devcontainer.json
      - ./.devcontainer/frontend/.vscode:/workspaces/senior-capstone-project/.vscode
      - /home/${HOST_USERNAME}/.ssh:/home/senior/.ssh:cached
      - /home/${HOST_USERNAME}/.config:/home/senior/.config:cached
    ports:
      - 3001:3000
    command: sleep infinity
    depends_on:
      - backend
      - mongo

  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: backend
    volumes:
      - .:/workspaces/senior-capstone-project
      - ./.devcontainer/backend/.vscode:/workspaces/senior-capstone-project/.vscode
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: sleep infinity
    depends_on:
      - mongo